package com.mycompany.practica8diu;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Mat;
import org.opencv.highgui.HighGui;
import org.opencv.imgcodecs.Imgcodecs;

public class VentanaInterna extends javax.swing.JInternalFrame {

    private final Mat imagen;
    JFileChooser fc = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes (*.jpg, *.png)", "jpg", "png");
    
    public VentanaInterna(String nombre, Mat imagen, int x, int y) {
        this.imagen = imagen;
        initComponents();
        BufferedImage imagenPintar = (BufferedImage) HighGui.toBufferedImage(imagen);
        jMenuBar1.setEnabled(false);
        jMenuBar1.setVisible(false);
        this.setTitle(nombre);
        this.setLocation(x, y);
        this.setSize(imagenPintar.getWidth(), imagenPintar.getHeight());
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setResizable(true);
        this.setClosable(true);
        lienzo1.setImagen(imagenPintar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new com.mycompany.practica8diu.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImage = new javax.swing.JMenu();
        itemGuardar = new javax.swing.JMenuItem();

        setMaximumSize(new java.awt.Dimension(1024, 750));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jMenuImage.setText("Imagen");

        itemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemGuardar.setText("Guardar");
        itemGuardar.setEnabled(false);
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        jMenuImage.add(itemGuardar);

        jMenuBar1.add(jMenuImage);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        int option = fc.showSaveDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            if(comprobarExtension(file)){
                Imgcodecs.imwrite(file.getPath(), imagen);
            } else {
                JOptionPane.showMessageDialog(this, "Sólo se pueden guardar archivos con extensión .jpg o .png.");
            }
        }
    }//GEN-LAST:event_itemGuardarActionPerformed
    
    private boolean comprobarExtension(File file){
        return file.getName().endsWith(".jpg") || file.getName().endsWith(".png");
    }
    
    public void menuUmbralVisible() {
        jMenuBar1.setEnabled(true);
        jMenuBar1.setVisible(true);
        itemGuardar.setEnabled(true);
        fc.addChoosableFileFilter(filter);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuImage;
    private com.mycompany.practica8diu.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables

    
}
